server:
  port: 8080

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/springcloud2-microservice?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      db-name: springcloud2-microservice

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.segema.devtool.domain
      
devtool: #开发工具
  location: E:/microservice-services
  developer: wangyong
  prefix: cola_

security:
  basic:
    enabled: false
