server:
  port: 8050
spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vangyong/microservice-segema.git/
          search-paths: config-repo
          username: vangyong
          password: wy513288
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/